language: node_js

node_js: '8.11.1'

install:
  - yarn install

script:
  - yarn test --coverage --detectOpenHandles

env:
  - NODE_ENV=test

cache:
  directories:
    - 'node_modules'

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - createuser pms-test -s -U postgres
  - createdb pms_test --username=pms-test

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
